[workspace]

members = [
    "Introduction/Getting started/*/",
    "A Basic Calculator/Introduction/*/",
    "A Basic Calculator/Integers/*/",
    "A Basic Calculator/Variables/*/",
    "A Basic Calculator/Branching if-else/*/",
    "A Basic Calculator/Panics/*/",
    "A Basic Calculator/Factorial/*/",
    "A Basic Calculator/Loops while/*/",
    "A Basic Calculator/Loops for/*/",
    "A Basic Calculator/Overflow and underflow/*/",
    "A Basic Calculator/Saturating arithmetic/*/",
    "A Basic Calculator/Conversions - as casting/*/",
    "Ticket v1/Introduction/*/",
    "Ticket v1/Structs/*/",
    "Ticket v1/Validation/*/",
    "Ticket v1/Modules/*/",
    "Ticket v1/Visibility/*/",
    "Ticket v1/Encapsulation/*/",
    "Ticket v1/Ownership/*/",
    "Ticket v1/Setters/*/",
    "Ticket v1/Stack/*/",
    "Ticket v1/Heap/*/",
    "Ticket v1/References in memory/*/",
    "Ticket v1/Destructors/*/",
    "Ticket v1/Outro/*/",
    "Traits/Introduction/*/",
    "Traits/Trait/*/",
    "Traits/Orphan rule/*/",
    "Traits/Operator overloading/*/",
    "Traits/Derive macros/*/",
    "Traits/Trait bounds/*/",
    "Traits/String slices/*/",
    "Traits/Deref trait/*/",
    "Traits/Sized trait/*/",
    "Traits/From trait/*/",
    "Traits/Associated vs generic types/*/",
    "Traits/Clone trait/*/",
    "Traits/Copy trait/*/",
    "Traits/Drop trait/*/",
    "Traits/Outro/*/",
    "Ticket v2/Introduction/*/",
    "Ticket v2/Enums/*/",
    "Ticket v2/Branching - match/*/",
    "Ticket v2/Variants with data/*/",
    "Ticket v2/Branching - if let and let-else/*/",
    "Ticket v2/Nullability/*/",
    "Ticket v2/Fallibility/*/",
    "Ticket v2/Unwrap/*/",
    "Ticket v2/Error enums/*/",
    "Ticket v2/Error trait/*/",
    "Ticket v2/Packages/*/",
    "Ticket v2/Dependencies/*/",
    "Ticket v2/thiserror/*/",
    "Ticket v2/TryFrom trait/*/",
    "Ticket v2/Error - source/*/",
    "Ticket v2/Outro/*/",
    "Ticket Management/Introduction/*/",
    "Ticket Management/Arrays/*/",
    "Ticket Management/Vectors/*/",
    "Ticket Management/Resizing/*/",
    "Ticket Management/Iterators/*/",
    "Ticket Management/Iter/*/",
    "Ticket Management/Lifetimes/*/",
    "Ticket Management/Combinators/*/",
    "Ticket Management/impl Trait/*/",
    "Ticket Management/impl Trait, pt.2/*/",
    "Ticket Management/Slices/*/",
    "Ticket Management/Mutable slices/*/",
    "Ticket Management/Two states/*/",
    "Ticket Management/Index trait/*/",
    "Ticket Management/IndexMut trait/*/",
    "Ticket Management/HashMap/*/",
    "Ticket Management/BTreeMap/*/",
    "Threads/Introduction/*/",
    "Threads/Threads/*/",
    "Threads/'static lifetime/*/",
    "Threads/Leaking memory/*/",
    "Threads/Scoped threads/*/",
    "Threads/Channels/*/",
    "Threads/Interior mutability/*/",
    "Threads/Ack pattern/*/",
    "Threads/Client/*/",
    "Threads/Bounded channels/*/",
    "Threads/Patching/*/",
    "Threads/Mutex, Send and Arc/*/",
    "Threads/RwLock/*/",
    "Threads/Without channels/*/",
    "Threads/Sync trait/*/",
    "Futures/Introduction/*/",
    "Futures/Asynchronous functions/*/",
    "Futures/Spawning tasks/*/",
    "Futures/Runtime/*/",
    "Futures/Future trait/*/",
    "Futures/Blocking the runtime/*/",
    "Futures/Async-aware primitives/*/",
    "Futures/Cancellation/*/",
    "Futures/Outro/*/",
    "Going further/Epilogue/*/",
]

exclude = [
    "**/*.yaml"
]
